#!/bin/bash

get_record_info() {
    local domain="$1"
    local subdomain="$2"

    local record_type=$(nslookup -type=ANY "$subdomain.$domain" | awk '/^'$subdomain'\./{print $4}')
    local destination=$(nslookup -type=A "$subdomain.$domain" | awk '/^Address:/{print $2}')

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    get_record_info "$domain" "www"
    get_record_info "$domain" "lb-01"
    get_record_info "$domain" "web-01"
    get_record_info "$domain" "web-02"
else
    get_record_info "$domain" "$subdomain"
fi
