#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get update -y
sudo apt-get install -y haproxy

sudo echo  'ENABLED=1' >> sudo etc/default/haproxy

# Edit configuration for servers
sudo sed -i "$ a\ \nfrontend load_balancer\n\tbind *:80\n\tdefault_backend myservers\n\nbackend myservers\n\tbalance roundrobin\n\tserver 165847-web-01 100.26.18.14 check port 80\n\tserver 165847-web-02 52.3.252.201 check port 80" /etc/haproxy/haproxy.cfg
# Restart HAproxy
sudo service haproxy restart
